### ISSUE TITLE
Feature request: Redirect on login

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#11]
Instead of redirecting users to the home page or a generic dashboard upon logging in, it should remember the last page the user was on before clicking on the 'Login' button. After successful login, users should then be redirected back to this page.

Thinking about a solution where we can add the redirect page to the login function
```
const { data, error } = await login({
    email: email.value,
    password: password.value,
    redirect: route
  })
  ```
  Where route could be string or route object.

**Comment by becem-gharbi** [comment]
Thanks for this suggestion,I can imagine 2 use cases:

First when the user enters a protected page. The module redirects to `login` page. The user enters his credentials. The module redirects back to the protected page.

Second when the user enters an unprotected page where the login UI is dynamic (visibility changes), perhaps a modal. The user enters his credentials. The module redirects back to the unprotected page.

Can you confirm my logic?

**Comment by becem-gharbi** [comment]
For the first use case, we can pass the protected path as query params to the login route.
For the second use case, we can add a redirect arg to the login handler as you have suggested.

On the login handler, the redirect path is equal by highest priority to
- The redirect argument
- The redirect query param
- The default `redirect.home`

**Comment by becem-gharbi** [comment]
Added on v0.1.4

**Comment by vanling** [comment]
@becem-gharbi query string redirect works like charm👍  thank you
