### ISSUE TITLE
Custom fields for users.me.read

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#2]
For a site I made i'm requesting extra information in the user object, with the Directus SDK i would use the following

```
.users.me.read({
  fields:[
    'email',
    'first_name',
    'last_name',
    'id',
    'role',
    'status',
    // groups
    'groups.groups_id',
    'groups.id',
    'groups.status',
    'groups.type',
    //favs
    'favourites.id',
    'favourites.collection',
    'favourites.item'
  ],
})
```

My thought was to crate an option here in the `fetchUser` that could be configured to add fields?

https://github.com/becem-gharbi/nuxt-directus/blob/ed7108052df1585a5587ea2478583de79416a83f/src/runtime/composables/useDirectusAuth.ts#LL67-L72C4

Any thoughts on this? I think this is simple enough that i can make a PR for if you want.

**Comment by becem-gharbi** [comment]
Good idea @vanling, i just want to add a note to take in consideration. The fetchUser method is meant to mutate the useUser state. The latter presents the type Partial of UserType.  By extending the response of user.me with relational fields, those properties wont benefit type suggestion in useUser.

**Comment by becem-gharbi** [comment]
I suggest changing the type definition of useUser,

```js
const useUser: () => Ref<(UserT & MyDirectusTypes["directus_users"]) | null> = () =>
    useState<(UserT & MyDirectusTypes["directus_users"]) | null>(
      "nuxt_directus_auth_user",
      () => null);
```

MyDirectusTypes is obtained as indicated in readme.

**Comment by vanling** [comment]
Thanks for that types, typescript is still alien too me ;)
