### ISSUE TITLE
PNPM?

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#31]
Question as I'm new to PNPM. Does anything need changed in your awesome module to be able to install it via PNPM since thats the package manager of choice from Directus now?

Excited to use this. Thanks!

**Comment by becem-gharbi** [comment]
It's just a personal preference. When using PNPM just make sure to install peer dependencies :)
```bash
pnpm config set auto-install-peers true
```

**Comment by BlackDahlia313** [comment]
> It's just a personal preference. When using PNPM just make sure to install peer dependencies :)
> 
> ```shell
> pnpm config set auto-install-peers true
> ```

awesome. thank you for the fast reply! setting this up as we speak!
