### ISSUE TITLE
List of auth providers doesn't list mine

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/nuxt-directus#33]
Hi! Thanks for your great module, works like a charm.

I have one problem though, since you build the SSO login link for directus with a fixed list of providers here: https://github.com/becem-gharbi/nuxt-directus/blob/c082b186081dc9701db73f5a851224dc4f87d546/src/runtime/composables/useDirectusAuth.ts#L15

I'm unable to use my provider, which has a custom/different name than the ones in the list.

Would it be possible to make this list just any string? Not sure why you would want to fix this list.

Cheers!

**Comment by keesvanbemmel** [comment]
I've noticed, it's not so much of a problem. In a component I can add pretty much any string I'd like 👯

**Comment by becem-gharbi** [comment]
Indeed you can use any name as it depends on directus configuration, you can ignore the warning with `@ts-ignore`. 
For type suggestion and better DX, I have defined a union type of the commonly used providers as suggested by the [docs](https://docs.directus.io/self-hosted/sso-examples.html).
