### ISSUE TITLE
Example of pulling item content

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#34]
Got auth setup on my own custom app. But I am wondering if you could provide an example on how to call a field from a collection. 

It hasn't clicked yet when looking at the demo.  Something like pulling a string or image from a collection. 

Thanks!

**Comment by BlackDahlia313** [comment]
I guess what I mean is I didnt see any example of the useDirectus  composable lol

**Comment by vanling** [comment]
@BlackDahlia313 Thanks for the tip. Will need to write something up for this soon.

it's basicly `const directus = useDirectus()` and directus wil work the same as the SDK from Directus https://docs.directus.io/reference/sdk.html

**Comment by BlackDahlia313** [comment]
> @BlackDahlia313 Thanks for the tip. Will need to write something up for this soon.
> 
> it's basicly `const directus = useDirectus()` and directus wil work the same as the SDK from Directus https://docs.directus.io/reference/sdk.html

ty btw
