### ISSUE TITLE
REQUEST: New SDK

### ISSUE THREAD

**Issue by Dominic-Marcelino** [becem-gharbi/nuxt-directus#36]
This module looks really promising but as there's a [new SDK ](https://docs.directus.io/packages/@directus/SDK%20(beta)/) coming soon (currently in beta) I'm wondering if you already do have plans to upgrade the module.

The new SDK doesn't rely on axios anymore but on fetch, so that some refactoring wold be necessary.

**Comment by becem-gharbi** [comment]
This module implements a custom Transport layer based on `$fetch` API. You can check it [here](https://github.com/becem-gharbi/nuxt-directus/blob/c082b186081dc9701db73f5a851224dc4f87d546/src/runtime/directus.ts#L196). 

If you can describe the benefits of migrating to the new SDK that would be helpful.

**Comment by Dominic-Marcelino** [comment]
The new SDK will:
- provide a better type support
- supports treeshaking due to it's modular approach
- have better SSR support (due to being completely stateless from the start)

And finally: Once it replaces the old one it will be the new "standard" (--> consistent DX for developers: no need to know / use both versions, feature-parity: new features will most likely only be released to the new SDK on long-term)

**Comment by becem-gharbi** [comment]
Great, so it's about performance. 
How can i find the source code, there is no `beta` branch on [sdk](https://github.com/directus/sdk).

**Comment by vanling** [comment]
They are in the process of moving the sdk to the mono repo: https://github.com/directus/directus/tree/main/packages/sdk
I think this is the PR: https://github.com/directus/directus/pull/18987 for new sdk

**Comment by becem-gharbi** [comment]
I have created a new branch `next` for a new `nuxt-directus` module based on the new Directus SDK. I will try to keep the same code structure and public APIs for compatibility. Your contributions is greatly appreciated :)

**Comment by BlackDahlia313** [comment]
> I have created a new branch `next` for a new `nuxt-directus` module based on the new Directus SDK. I will try to keep the same code structure and public APIs for compatibility. Your contributions is greatly appreciated :)

great work!

**Comment by becem-gharbi** [comment]
Hey everyone, I have added a Todos list to readme for the new module. Let me know if you have remarks.

**Comment by vanling** [comment]
- Consider the usage of $fetch over fetch for transport
> I Think that sticking with $fetch is important, it has everything covered/optimized to run on different platforms (edge etc) and this one of the main reasons I use and recommend this package over others.
>> edit: **not sure if its currently possible to overwrite this in the new sdk**
- Consider usage of realtime APIs with SSR.
> think feature parity would be the first goal. I like to play with websockets some day, but this would be great for a future update.

**Comment by becem-gharbi** [comment]
It seems like te new sdk uses `globalThis.fetch` for data fetching, [reference](https://github.com/directus/directus/blob/1ddc172de3964fc2bd7f51d067d5d31fd216e4ae/sdk/src/utils/request.ts#L29). So it uses the runtime's fetch API. That means it's platform agnostic and probably `$fetch` is not needed. I'm not 100% sure if I'm correct.

**Comment by BlackDahlia313** [comment]
> It seems like te new sdk uses `globalThis.fetch` for data fetching, [reference](https://github.com/directus/directus/blob/1ddc172de3964fc2bd7f51d067d5d31fd216e4ae/sdk/src/utils/request.ts#L29). So it uses the runtime's fetch API. That means it's platform agnostic and probably `$fetch` is not needed. I'm not 100% sure if I'm correct.

I believe you are correct in your thinking on this. 

> I like to play with websockets some day, but this would be great for a future update.

I’m excited for some realtime features in the future like community voting

**Comment by becem-gharbi** [comment]
A new release `0.1.1` is [here](https://github.com/becem-gharbi/nuxt-directus/releases/tag/v0.1.1-next). Authentication and Rest composables are implemented with SSR. The other composables will be added on the next release.

**Comment by becem-gharbi** [comment]
The old module is now under `version-1` branch and the new one under `main`. 
I'm closing this issue, for future ones related to old module I will add `version-1` label.
