### ISSUE TITLE
Question - user info not persistent & refresh request fail

### ISSUE THREAD

**Issue by kadlinobit** [becem-gharbi/nuxt-directus#38]
Hi, 
I discovered your nuxt-directus plugin and it seems perfect - using just plain directus SDK and introducing simple authentication. 

But when I was experimenting with it I had some unexpected issues. Maybe I just don't understand properly how it is supposed to work. 

1. I am able to log in and then display user info (using `useUser` composable). But when I refresh the page in the browser, user info is gone. Is that how it's supposed to be? 

2. Refresh request is not working. When the plugin sends the request, there is no JWT token attached. There is this error response from Directus: 

```json
{
    "errors": [
        {
            "message": "Invalid payload. \"refresh_token\" is required in either the JSON payload or Cookie.",
            "extensions": {
                "code": "INVALID_PAYLOAD",
                "reason": "\"refresh_token\" is required in either the JSON payload or Cookie"
            }
        }
    ]
}
```

I can see that there is the `auth_token` cookie set, but just for localhost:3000. 
![image](https://github.com/becem-gharbi/nuxt-directus/assets/46809506/3ea896d9-d08f-4496-b339-8faecc61024a)

I am using the default ports for both nuxt (3000) and directus (8055). 

I appreciate any advice about what I'm doing wrong (or maybe just don't understand the logic behind this plugin). 

Thanks!

**Comment by becem-gharbi** [comment]
Thanks @kadlinobit for the feedback!
I remember having a similar issue. It's related to the `localhost` domain. In development it should an ipv4 address. I have mentioned this in **Notes**. Please replace all `localhost` with `127.0.0.1` in Nuxt and Directus configurations and let me know if that helps.

**Comment by vanling** [comment]
_This is a small writeup for when you are using a Directus that you host online on a domain like `api.mydomain.ext`_
I'm not sure if this helps in your case, but i wanted to write a guide anyway, will use this comment as my first draft. Maybe this is helpful to you or anyone else in the meantime.  

When using MACOS i am using '[mkcert](https://formulae.brew.sh/formula/mkcert)' via homebrew to have an actual domain with https. This helps greatly with cookies/authentication issues.

## Nuxt @ local.mydomain.ext
- Install and setup mkcert. `brew install mkcert`
- Create a cert `mkcert local.mydomain.ext` usually add this in the nuxt project and add to gitignore.
- Add `local.mydomain.ext` to `/etc/hosts` to point to 127.0.0.1
- change the dev command in `package.json`
```
"dev": "NODE_TLS_REJECT_UNAUTHORIZED=0 nuxt dev --host local.mydomain.ext --https --ssl-cert local.mydomain.ext.pem --ssl-key local.mydomain.ext-key.pem",
"dev2": "nuxt dev",
```

## Directus config @ api.mydomain.ext
```
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"
REFRESH_TOKEN_COOKIE_DOMAIN=".mydomain.ext"
REFRESH_TOKEN_COOKIE_SECURE="true"
REFRESH_TOKEN_COOKIE_SAME_SITE="None"
```

## nuxt-directus config
```
 directus: {
    baseUrl: 'https://api.mydomain.ext', // Directus app base url
    nuxtBaseUrl: 'https://local.mydomain.ext:3000', // Nuxt app base url
    auth: {
      enabled: true,
      enableGlobalAuthMiddleware: false, // Enable auth middleware on every page
      refreshTokenCookieName: 'directus_refresh_token',
      defaultRoleId: 'tbd', // Role id assigned for new registered users
      redirect: {
        login: '/auth/login', // Path to redirect when login is required
        logout: '/auth/logout', // Path to redirect after logout
        home: '/', // Path to redirect after successful login
        resetPassword: '/auth/resetPassword', // Path to redirect for password reset
        callback: '/auth/callback', // Path to redirect after login with provider
      },
    },
```

_Unfortunately i have no knowledge for windows for this setup._

**Comment by kadlinobit** [comment]
- Using 127.0.0.1 instead of localhost helped with persisting the user and refresh token as well. Thanks @becem-gharbi! 
- I will try running the dev env on https, nice guide, thank you @vanling!

**Comment by kadlinobit** [comment]
Hi @vanling, 
just a follow-up question - how do you start Directus with **https** in development mode? I can't find any info about that. Is that even possible just via `npx directus start`, or do I need some proxy server in front of Directus to handle secure communication?

**Comment by vanling** [comment]
@kadlinobit 

In my package.json i replaced the default nuxt dev  command into 
`NODE_TLS_REJECT_UNAUTHORIZED=0 nuxt dev --host local.mydomain.nl --https --ssl-cert local.mydomain.nl.pem --ssl-key local.mydomain.nl-key.pem`

`NODE_TLS_REJECT_UNAUTHORIZED=0` for allowing nodejs to connect via https (not sure if still needed)
`--host local.mydomain.nl` to change locahost to local.mydomain
`--https` should enable https 
`--ssl-cert local.mydomain.nl.pem --ssl-key local.mydomain.nl-key.pem` is for the certificate


_my scripts in package json_
```
 "scripts": {
    "build": "nuxt build",
    "dev": "NODE_TLS_REJECT_UNAUTHORIZED=0 nuxt dev --host local. mydomain.nl --https --ssl-cert local. mydomain.nl.pem --ssl-key local. mydomain.nl-key.pem",
    "dev2": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "release-patch": "npx changelogen@latest --release --patch",
    "release-minor": "npx changelogen@latest --release --minor",
    "release-major": "npx changelogen@latest --release --major",
    "lint:js": "eslint --ext \".ts,.vue,.js\" --ignore-path .eslintignore .",
    "lint:js:fix": "eslint --fix --ext \".ts,.vue,.js\" --ignore-path .eslintignore .",
    "lint:prettier": "prettier --check . --fix --ignore-path .prettierignore",
    "lint": "npm run lint:js && npm run lint:prettier",
    "lintfix": "prettier --write --list-different . && npm run lint:js --fix",
    "clean": "rm -rf .nuxt dist .output"
  },
```

**Comment by vanling** [comment]
@kadlinobit _(deleted my other reply because I misread your question)_

When sharing my setup, I hadn't considered local Directus. I've always configured my Directus online rather than locally. However, considering Directus now offers convenient tools for schema import/export, I might revisit setting it up locally for development.

For HTTPS with Directus, one option is using a local nginx proxy. Yet, managing HTTPS can be challenging. You might achieve this with mkcert and a custom nginx config, or use nginxproxymanager via Docker to proxy Directus to port 443.

That said, for local development, I'd recommend using 127.0.0.1 on both ends if it suits you. My advice was primarily for interfacing with an online Directus instance.

Lastly, rather than using the npm run dev scripts I mentioned, simply modify the script in package.lock to `"dev": "nuxt dev --host 127.0.0.1"` for a tidier configuration.

_edited: chatgpt rewrote my unhinged english sentences._

**Comment by kadlinobit** [comment]
@vanling 
OK understood, still thanks for the guide, I'll definitely use it one time. I did a little bit more research and found this discussion:

https://github.com/directus/directus/discussions/3307

Seems like the easiest solution for local development with HTTPS is using caddyserver and reverse proxy. I'll leave it here in the comment for reference.

**Comment by becem-gharbi** [comment]
New update on this issue https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.0.4

**Comment by moseskamau338** [comment]
Am having a similar problem where once I log in and refresh the page, am logged out immediately. I've tried a setup with both Directus and my front-end app on the same domain (localhost) and in separate domains. What am I missing?
