### ISSUE TITLE
SSO Callback

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#39]
Implementing the callback just like in the demo on my own project just takes me to the callback page like so:

![image](https://github.com/becem-gharbi/nuxt-directus/assets/44903742/0072a459-74e8-47aa-a56f-27e4f6384bb5)

It just sits there. 

Do I need a callback page or can I just redirect to the dashboard I made?

**Comment by BlackDahlia313** [comment]
setting it to the dashboard directly causes some really weird issues so im not sure what I am missing here :p

**Comment by becem-gharbi** [comment]
A distinct `callback` page is required. If the login is successfull the module [redirects](https://github.com/becem-gharbi/nuxt-directus/blob/cc7789aa70082fb23904f9aef5d8d173099e2369/src/runtime/middleware/common.global.ts#L21) to `home` page or previously visited protected page. Otherwise, the `callback` page gets rendered with an error message as query parameter.

**Comment by BlackDahlia313** [comment]
> A distinct `callback` page is required. If the login is successfull the module [redirects](https://github.com/becem-gharbi/nuxt-directus/blob/cc7789aa70082fb23904f9aef5d8d173099e2369/src/runtime/middleware/common.global.ts#L21) to `home` page or previously visited protected page. Otherwise, the `callback` page gets rendered with an error message as query parameter.

So I have the SSO login working and I have the callback set, but its just sitting on the spinning page.  Not sure what I am missing.


Using this as the example:
https://github.com/becem-gharbi/nuxt-directus/blob/main/demo/pages/auth/callback.vue


email/password does work though just fine.

**Comment by becem-gharbi** [comment]
Can you check refresh token cookie on SSO login?

**Comment by BlackDahlia313** [comment]
> Can you check refresh token cookie on SSO login?

I do see it when it returns from the provider:

![image](https://github.com/becem-gharbi/nuxt-directus/assets/44903742/8e9de75b-5280-40f6-8631-51b369dd109d)

its also set like the example in the env:

```
REFRESH_TOKEN_COOKIE_DOMAIN="directus.mysite.com" # Replace XXXX with the domain of your Directus instance. For example "directus.myserver.com"
REFRESH_TOKEN_COOKIE_SECURE="true"
REFRESH_TOKEN_COOKIE_SAME_SITE="None"
```

**Comment by BlackDahlia313** [comment]
I do notice that your directus_refresh_token in your demo is set to your main tld domain while mine is set to directus install. could that be it?

trying to change that to *.mydomain didnt do it either.

**Comment by becem-gharbi** [comment]
Directus and Nuxt apps should have the same domain name because cookie's `sameSite` is set to [lax](https://github.com/becem-gharbi/nuxt-directus/blob/0fac7b8a2ef13dc6234802d2ccfe97e28471267e/src/runtime/directus.ts#L170). When the domains are not the same refresh token cookie will not be sent to Directus. This is mentioned in **Notes**.

**Comment by BlackDahlia313** [comment]
> Directus and Nuxt apps should have the same domain name because cookie's `sameSite` is set to [lax](https://github.com/becem-gharbi/nuxt-directus/blob/0fac7b8a2ef13dc6234802d2ccfe97e28471267e/src/runtime/directus.ts#L170). When the domains are not the same refresh token cookie will not be sent to Directus. This is mentioned in **Notes**.

they do have the same domain name. unless you are referencing subdomains?

Not sure how else that would be possible hosting directus on rails and the frontend on vercel with it being the same tld and not split by subdomains?

So I just et the samesite to lax and site the domain to just the tld. its redeploying now.

Edit: that didnt do it either. im just confused on this part I think. same tld. and just a copy of your source. has to be a setting in directus than

**Comment by becem-gharbi** [comment]
Is SSR enabled?

**Comment by BlackDahlia313** [comment]
> Is SSR enabled?

deployed on vercel and not seeing anything set to static for the auth pages.

**Comment by becem-gharbi** [comment]
I'm not able to reproduce the issue in any case. Please check the following:
- Clear cookies and local storage.
- Setup Directus env
```js
  REFRESH_TOKEN_COOKIE_DOMAIN= "bg-tech.tn" # The shared domain name
  REFRESH_TOKEN_COOKIE_SAME_SITE= Lax
  REFRESH_TOKEN_COOKIE_SECURE= true
```
- These cookies stored upon SSO login
![image](https://github.com/becem-gharbi/nuxt-directus/assets/99251251/3caaf683-e805-49be-95cb-acac5c3e4c59)

**Comment by becem-gharbi** [comment]
I'm not able to reproduce the issue in any case. Please check the following:
- Clear cookies and local storage.
- Setup Directus env
```js
  REFRESH_TOKEN_COOKIE_DOMAIN= "bg-tech.tn" # The shared domain name
  REFRESH_TOKEN_COOKIE_SAME_SITE= Lax
  REFRESH_TOKEN_COOKIE_SECURE= true
```
- These cookies stored upon SSO login
![image](https://github.com/becem-gharbi/nuxt-directus/assets/99251251/3caaf683-e805-49be-95cb-acac5c3e4c59)

**Comment by BlackDahlia313** [comment]
yep same settings. When I use the frontend login button and it sits at callback. If load directus in another tab, it knows im logged in.

I see your screenshot includes auth_expires and auth_token. Is that something manually set somewhere?

everything else looks like but I am missing the auth_expires, auth_token and auth_expires_at. Is that a setting in directus that needs to be set manually?

![image](https://github.com/becem-gharbi/nuxt-directus/assets/44903742/6e329f27-89a5-4684-8f98-004a69860849)


the auth_token etc does show up when logging in via email/password tho.

**Comment by BlackDahlia313** [comment]
`await sdk.auth.refresh();`

this wasn't in the callback.vue i scrapped from you. Once I added this, it logged me into the dashboard perfectly.  :)

**Comment by BlackDahlia313** [comment]
whats interesting is now when accessing logout it will do the logout. But I can still access dashboard. wonder if its the auth expires

because after a small amount of time it seems to expire than force back to dashboard

**Comment by becem-gharbi** [comment]
So the refresh token cookie exists and the access token cookie is not. This leads to this unmet [condition](https://github.com/becem-gharbi/nuxt-directus/blob/0fac7b8a2ef13dc6234802d2ccfe97e28471267e/src/runtime/directus.ts#L52). Please make sure that `redirect.callback` config option starts with  `/`.

**Comment by BlackDahlia313** [comment]
Oh I got it working. It needed the auth refresh added to callback. :)
