### ISSUE TITLE
Logout user if token refresh fails

### ISSUE THREAD

**Issue by kadlinobit** [becem-gharbi/nuxt-directus#40]
Hi, 
I have forced token refresh to fail on purpose to see how this case is handled. I can see that after unsuccessful refresh the auth cookies are gone, but useUser() still keeps the user data, until I refresh the browser window. 

Is it somehow possible to logout user automatically in case of token refresh failure?

**Comment by becem-gharbi** [comment]
Thanks for noticing this behaviour. Indeed the app should logout if the refresh token expires. On the [transport](https://github.com/becem-gharbi/nuxt-directus/blob/0fac7b8a2ef13dc6234802d2ccfe97e28471267e/src/runtime/directus.ts#L103) function we can check for `unauthorized` status code and automatically perform logout.

**Comment by kadlinobit** [comment]
@becem-gharbi 

OK I tested this approach and it works: 
```js
        .catch((error) => {
          if (path === "/auth/refresh" && method === "POST") {
            clearNuxtState("nuxt_directus_auth_user");
          }

          throw new TransportError<T>(error, {
            raw: error.data,
            errors: error.data["errors"],
            status: error.status,
          });
        });
```
I can make a pull request for this if you want. 

But I was thinking whether some kind of event could be fired - so we could catch it on frontend and maybe display an error message ("refresh failed, you've been logged out"). What is your opinion?

**Comment by becem-gharbi** [comment]
Great, maybe we can add a hook `onError` and leave it to the developer to decide.

Edit: I mean in any case the user state should be cleared, But the redirection can be to `logout` page or a user defined page with an error message.

**Comment by becem-gharbi** [comment]
Maybe we just add a `loggedOut` redirect option
```js
if (path === "/auth/refresh" && method === "POST") {
 clearNuxtState("nuxt_directus_auth_user");
 const { logout, loggedOut } = publicConfig.auth.redirect;
 await navigateTo(loggedOut || logout);
 throw new Error("refresh failed, you've been logged out");
 }
```

Edit: I made these changes on the new `v1` release.
