### ISSUE TITLE
Logout 400

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#41]
Great new release. Just moved to the new beta and for some reason anytime I call logout its giving me a 400 error.

Updated logout to use the method.

**Comment by BlackDahlia313** [comment]
checking via deployment as I was seeing this on localhost and want to test on tld first

**Comment by BlackDahlia313** [comment]
As suspected doesnt happen when deployed on the tld. great work with the recent updates!

**Comment by becem-gharbi** [comment]
You’re welcome
