### ISSUE TITLE
Draft: Collection of Issues with authentication.

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#44]
# working on this issue to complete it and test some more.

_Going to collect some issues with authentication._ 

_There is a big chance issues can still be caused upstream by  the SDK_
- https://github.com/directus/directus/pull/19354

**Currently experiencing issues with** 
- automatic refreshing of tokens (with or without provider)
- logout (provider) with custom cookiename (refresh token not found)

# Testing different scenario + results
- access_token is session based, 
  - closing the browser and reopening the site should in theory get a new access_token with the refresh_token in the cookie? ❌
  - Should a refresh be added here when there is a refresh token but no access token? https://github.com/becem-gharbi/nuxt-directus/blob/1bf727868c1c48d440590f29b44eb840ae2b749b/src/runtime/plugins/auth.ts#L44
  - or here? when it tries to use access_token, but we only have refresh_token-> get a new access token https://github.com/becem-gharbi/nuxt-directus/blob/1bf727868c1c48d440590f29b44eb840ae2b749b/src/runtime/composables/useDirectusAuth.ts#L170
- _(seperate issue for later) Redirects are only query string based, makes it harder to do some more advanced middleware login/logout flows_

## login()
- [x] auto refresh after inactivity 
- [x] navigate to other page with directus content after inactivity
- [x] after inactivity (15min) -> refresh the browser -> tokens still exist but user data not filled -> refresh browser again -> user data filled. ** **will try to create a better reproduction path for this one**

## loginWithProvider()
- [x] refresh after inactivity  - Works✅ 
- [x] navigate to other page with directus content after inactivity

**Comment by becem-gharbi** [comment]
Just to note that authentication composable is totally independent of Directus SDK. 
Edit: I mean the logic and storage behind refreshing access token.

**Comment by vanling** [comment]
Yes thanks!.

I have used the direct logout of the sdk before so there was no redirect, i will revert back to the "normal" logout for now, but it might be nice to add logout and login functions that could work without redirecting so the users could do this themselves.

I will revert to the logout in the composable for now to keep debugging/testing more simple.

**Comment by becem-gharbi** [comment]
I had created this flowchart of the refresh logic, it might help

![flowchart](https://github.com/becem-gharbi/nuxt-directus/assets/99251251/aeb826f7-a123-4369-a87c-d65095c75e14)

**Comment by vanling** [comment]
@becem-gharbi Nice! thanks.

I might end up closing this issue later when i find out its all because of me :P Things are being a bit hectic with 2 bigger projects (one with direct login and one with provider login)  It's a pretty big migration with the new sdk.

For now it looks like the project with LoginWithProvider() path seems to be working.

The normal login() application -> https://interiorboards.nl/inspiratie i can lower the token time later tonight to test faster.
1. login
2. stay on a page for 15+ min
3. after token expired, go to a page with data that requires the token
4. Directus data is public instead of user-based
5. refresh and user-based-data is back

**_Once i find something that actually is broken or can be improved I will make a fresh new issue_**

**Comment by vanling** [comment]
Ok closing this one for now, thanks for [Rubber ducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging) and thinking with me. 

I will check/test one more thing and if that keeps giving issues I will make new issue.
