### ISSUE TITLE
In a new session that has a refresh token, no new access token is fetched.

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#45]
**Summary:**
Access tokens are lost upon reopening the browser, while refresh tokens persist. 

**Steps to Reproduce:**
1. Log in to the site and obtain the access and refresh tokens.
2. Quit the browser completely.
3. Reopen the browser and navigate back to the site.
4. Observe that the user is no longer logged in; the access token is gone (since it's session-based), but the refresh token still exists.

**Expected Behavior:**
In version 1, all tokens used to be stored in cookies. Although I appreciate the new approach with session-based tokens, it's problematic that the browser still retains the refresh token while losing the access token. Ideally, the system should be able to obtain a new access token using the existing refresh token without requiring the user to log in again.

**Possible Solution:**
I suggest implementing a mechanism that retrieves an access token during initialization if a refresh token exists and the access token is either empty or gone. This would maintain user authentication across browser sessions without compromising the benefits of using session-based tokens.

**Comment by becem-gharbi** [comment]
The problem with the possible solution is that when SSR is disabled. In this case we cannot know whether or not the refresh token exists, so the refresh call will always be made.

Does a large max-age, let's say a year, would solve the issue?

**Comment by vanling** [comment]
Hmmm.. not sure if setting any max-age is ok, the session based access token is perfect way to do it. 

Is there no place to do a check for access_token @ client-side? 

How is the Directus app itself doing this? There is only a refresh_token there, with the access token being stored in browser-memory(session based). And the first time you open it, it does a /api/refresh  and logs you in.

_I can also try this in the app.vue by calling getToken and fetchUser manually._

**Comment by becem-gharbi** [comment]
Directus data studio always perform refresh call at page load. I believe that this is acceptable for an administration usage but at scale this would be inefficient.

**Comment by becem-gharbi** [comment]
Another solution would be to check if the page is protected (with auth middlewware) and only in this case perform refresh call.
Edit: I'm not sure if we can get page meta at plugin level.

**Comment by vanling** [comment]
>Directus data studio always perform refresh call at page load. I believe that this is acceptable for an administration usage but at scale this would be inefficient.

True! but this worked flawlessly in v1 :(, so there must be a way somehow.

>Another solution would be to check if the page is protected (with auth middlewware) and only in this case perform refresh call.

that sounds promising! 

**edit:** altho This would not work for login (isAuthenticated)  and getting user data on homepage in the header for example

**Comment by vanling** [comment]
altho This would not work for login (isAuthenticated)  and getting user data on homepage in the header for example

**Comment by becem-gharbi** [comment]
Another solution would be to store access token in local storage.  On page load:
- When SSR enabled, the access token will always be refreshed server-side.
- When SSR disabled, the access token will be retrived from local storage and the logic stays the same.

**Comment by becem-gharbi** [comment]
I have create `fix-token-storage` branch. You can check [changes](https://github.com/becem-gharbi/nuxt-directus/compare/main...fix-token-storage). 
- The access token is stored only to local storage. (On SSR it's passed via cookie, then on client side the cookie is removed and stored instead to local storage)
- On page load, the access token is refreshed if it exists. (Doesn't need to be expired)

**Comment by vanling** [comment]
I think this will work but I'm not sure if LocalStorage is the way to go.
I will think and play with this more later this day

**Comment by becem-gharbi** [comment]
I don't see any alternatives without having to add extra complexity to code. To recapitulate these are the options I see:
- Store access token in a long-lived cookie, no vulnerability with that as it's a short-lived token.
- Store access token in local storage, perhaps XSS vulnerability added but the developer should be aware of that.

**Comment by becem-gharbi** [comment]
Just pushed a new release that adds option to configure max-age of access token cookie. https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.2.4-beta

**Comment by vanling** [comment]
Testing and looks to be working! 
max-age is fine, I forgot about the token being short lived which makes this ok.

Testing with token that lives 2 minutes, reopened browser after 20 minutes, still logged in 🚀 🎉

**Comment by becem-gharbi** [comment]
New release [2.2.5](https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.2.5-beta) to address this issue:
- Store access token to a session cookie
- Store logged_in state in localStorage
- On page load, If logged_in is `yes` perform refresh

![flow](https://raw.githubusercontent.com/becem-gharbi/nuxt-directus/main/design/2-2-5.png)

**Comment by vanling** [comment]
@becem-gharbi 
> Store logged_in state in localStorage
> On page load, If logged_in is yes perform refresh

That's a creative solution i love <3 awesome
