### ISSUE TITLE
500 error. failed to find clearNuxtState

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#47]
Seeing this when upgrading to 2.3.

` ERROR  [unimport] failed to find "clearNuxtState" imported from "#imports" (x4) `

**Comment by BlackDahlia313** [comment]
2.2.6 is working fine. And I do see the addition of the clearNuxtState in 2.3, but thats the error I'm geting.

**Comment by becem-gharbi** [comment]
This is weird, try to delete .nuxt folder and reinstall the module.

**Comment by BlackDahlia313** [comment]
> This is weird, try to delete .nuxt folder and reinstall the module.

trying that now

edit:

no. same concern. 

![image](https://github.com/becem-gharbi/nuxt-directus/assets/44903742/0dfb1327-d338-4b0b-b1bd-665831cebd11)

![image](https://github.com/becem-gharbi/nuxt-directus/assets/44903742/dc28b56b-d1e2-403a-b6dc-ff9c286225fa)

**Comment by becem-gharbi** [comment]
I was not able to reproduce the issue. However I released a patch with alternative implementation. https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.3.1-beta

**Comment by BlackDahlia313** [comment]
> I was not able to reproduce the issue. However I released a patch with alternative implementation. https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.3.1-beta

this solved the concern. thank you for such a fast reply and patch.
