### ISSUE TITLE
Missing aggregate() function from Nuxt's auto import

### ISSUE THREAD

**Issue by Vincent-HD** [becem-gharbi/nuxt-directus#53]
Hi,
I'm noticing that there isn't `aggregate()` function, so it's impossible to use it with `useDirectusRest()`, for now I installed the SDK and I imported the aggregate function myself.

I tried to understand why in the repo, but honestly I don't understand how auto import works in Nuxt (part of why I'm not a fan of it), is it supposed to globally import all functions from what you are using inside composables folder inside your module ?

**Comment by becem-gharbi** [comment]
The SDK is already installed. I will add this method for auto import. For now you can manually import it.

```ts
import { aggregate } from '@directus/sdk'

```
