### ISSUE TITLE
useDirectusRest picking up wrong DirectusSchema global type

### ISSUE THREAD

**Issue by Vincent-HD** [becem-gharbi/nuxt-directus#55]
Hi,
I added a directus.d.ts like in your starter, but useDirectusRest is picking up your global instead of mine
```typescript
declare global {
  interface DirectusSchema {}
}
```
![image](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/713728c2-ffe8-4e92-b385-9aa6de513fc6)

![Code_RBkvb06eih](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/c199fc25-7dcf-4638-94d1-ee698d7c9368)

Do you know in which order (if there is) d.ts are overriding each other ?

**Comment by becem-gharbi** [comment]
Hi, did you have exported the type?

```ts
declare global {
  interface DirectusSchema {}
}

export {}
```

**Comment by Vincent-HD** [comment]
Yes, you can see it in the video.
I think I found why, to use aggregate function since it wasn't in the extension before, I installed the SDK, and I upgraded it to v12, but the extension still uses v11, so they must of change something related to types in v12, downgrading it to v11 seems to solves it
