### ISSUE TITLE
Command imports is missing user-utils

### ISSUE THREAD

**Issue by Dominic-Marcelino** [becem-gharbi/nuxt-directus#56]
Hey again 👋🏼

The command import is missing the user-util commands ([view in directus SDK](https://github.com/directus/directus/blob/main/sdk/src/rest/commands/utils/users.ts))

https://github.com/becem-gharbi/nuxt-directus/blob/2225380d72b1469cfd403d20d9a29aa00c58e6a6/src/module.ts#L149-L155

I haven't checked all commands, but in general it feels like a bunch of commands are missing. 

What do you think about replacing the list and importer with [`addImportsDir `](https://nuxt.com/docs/guide/going-further/modules/#injecting-composables-with-addimports-and-addimportsdir) to always have all rest-commands available?

**Comment by becem-gharbi** [comment]
Hi, 

This will also register non-command APIs for auto-import. To be honest I'm not working with Directus currently, so I'm not fully familier with commands. I suggest opening a PR to add the ones you find commonly used.

**Comment by Dominic-Marcelino** [comment]
> To be honest I'm not working with Directus currently,

On no, sad to read 🥲

> This will also register non-command APIs for auto-import.

I thought this could be resolved by using the sdk rest export, but I just noticed that this also includes the type definitions
https://github.com/directus/directus/blob/8f1a7a83fd3bde9043137893d0478dfd76577f41/sdk/package.json#L35-L38

For now I'll probably go with importing the commands directly from the sdk, as it's hard to keep the import list up to date manually
