### ISSUE TITLE
Possible bug: No fields returned when I add a large set of fields to query

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#6]
Upon using an array to add fields in the query, the query tends to become considerably lengthy, particularly when there are more than 15-ish fields. I managed to resolve this issue for myself by incorporating the `.join(',')` function; however, this solution may inadvertently introduce unanticipated issues for other users.

There are two methods to include fields in the query:

Utilizing a string: `fields: "field1,field2,field3,field4"`
Utilizing an array: `fields: ['field1','field2','field3','field4']`
The root of the problem appears to be related to the QS library, specifically the line const query = qs.stringify(options?.params);. Unfortunately, I am yet to identify a definitive fix for this issue.

Here is an example of fields that caused problems when used with nuxt-directus, but did not pose any issues with the SDK itself:
```
export const fieldsUserSimple = [
  'email',
  'first_name',
  'last_name',
  'id',
  'role',
  'status',
  'groups.groups_id',
  'groups.id',
  'groups.status',
  'groups.type',
  'favourites.id',
  'favourites.collection',
  'favourites.item',
  'broadcasts.id',
  'broadcasts.broadcasts_id',
  'user_module_state.id',
  'user_module_state.video_time',
  'user_module_state.status',
  'user_module_state.date_completed',
  'user_module_state.custom_state',
  'user_module_state.module_content',
    // >>>>> it was broken after adding this ones.
  'user_module_state.module_content.id',
  'user_module_state.module_content.module',
  'user_module_state.module_content.duration',
]
```

**Comment by vanling** [comment]
## Some debugging

Output of 
```
const query = qs.stringify(options?.params);
console.log(query);
```

**large array** ❌

`fields[]=email&fields[1]=first_name&fields[2]=last_name&fields[3]=id&fields[4]=role&fields[5]=status&fields[6]=groups.groups_id&fields[7]=groups.id&fields[8]=groups.status&fields[9]=groups.type&fields[10]=favourites.id&fields[11]=favourites.collection&fields[12]=favourites.item&fields[13]=broadcasts.id&fields[14]=broadcasts.broadcasts_id&fields[15]=user_module_state.id&fields[16]=user_module_state.video_time&fields[17]=user_module_state.status&fields[18]=user_module_state.date_completed&fields[19]=user_module_state.custom_state&fields[20]=user_module_state.module_content&fields[21]=user_module_state.module_content.id&fields[22]=user_module_state.module_content.module&fields[23]=user_module_state.module_content.duration`

_returns array with id's only_


**string csv** ✅
`fields=email,first_name,last_name,id,role,status,groups.groups_id,groups.id,groups.status,groups.type,favourites.id,favourites.collection,favourites.item,broadcasts.id,broadcasts.broadcasts_id,user_module_state.id,user_module_state.video_time,user_module_state.status,user_module_state.date_completed,user_module_state.custom_state,user_module_state.module_content,user_module_state.module_content.id,user_module_state.module_content.module,user_module_state.module_content.duration`

_returns array with every field i selected_

**Comment by becem-gharbi** [comment]
I was not able to reproduce the issue, however i removed qs module and used ofetch query serialization. I've pushed a new release you can test again.

**Comment by vanling** [comment]
Awesome work! I will test tomorrow morning.

**Comment by vanling** [comment]
Updated to latest version. Changed `userFields: fieldsUserSimple.join(','),` into `userFields: fieldsUserSimple,` and everything seems to be working fine now!   🎉
