### ISSUE TITLE
Struggling to get filters on parent and child collections working.

### ISSUE THREAD

**Issue by laportem** [becem-gharbi/nuxt-directus#63]
I have a collection called Topics and it has a one-to-many relationship with another collection called Articles. The one-to-many field name on Posts to Articles is called “articles”

Using t  "@bg-dev/nuxt-directus": "2.3.1-beta", REST, I want to query for Topics where Status = “published” and for Topics ->articles where Status = “published”

I can filter Topics but filtering on Topics ->articles does not seem to work at all
Here is my code:
`
  const fields = ['id', 'topic', 'default_open', { articles: ['id', 'title', 'status'] }];
  const filter = { status: { _eq: 'published' } };
  const _res = await useDirectusRest(readItems('learn_topics', { fields, filter }));
`

**Comment by becem-gharbi** [comment]
Hi, please make sure to upgrade to latest stable release. Regarding the REST usage, please refer to Directus docs as the module directly exposes the `request` API. https://docs.directus.io/reference/introduction.html
