### ISSUE TITLE
Update SDK to v13

### ISSUE THREAD

**Issue by Dominic-Marcelino** [becem-gharbi/nuxt-directus#64]
It's that time again where the SDK had a version bump from v12 to v13. The main reason for the increase was the possible breaking changes due to adding support for reading/updating extensions in the SDK (came with directus release v10.7.0). Therewith I don't think this module needs any changes, as but haven't tested it yet.

**Apart from that, these are the changes that could have an impact on the module:**
- [Type-Fixes](https://github.com/directus/directus/pull/19881)
- [New Asset functions](https://github.com/directus/directus/pull/20041) (probably unimportant, as the module doesn't includes a full function-map either)

[Whole changelog](https://github.com/directus/directus/releases)

Do you want me to open a PR, or will you check / test it yourself? :)

Thanks as always!

**Comment by becem-gharbi** [comment]
Thanks for keeping this module in sync with the latest SDK updates, really appreciated :)

If you can open a PR, that would be very helpful
