### ISSUE TITLE
useCookie is not defined

### ISSUE THREAD

**Issue by BlackDahlia313** [becem-gharbi/nuxt-directus#66]
Finally getting around to updating this from 2.0.1 to 2.1.1 and on the latest version I am seeing this now. I don't see anything different in the config thats needed for nuxt. Am I supposed to be setting something new on pages now?

**Comment by becem-gharbi** [comment]
I forgot to import it, https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.1.2

**Comment by BlackDahlia313** [comment]
> I forgot to import it, https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.1.2

thank you. everything is working again as expected!
