### ISSUE TITLE
How does this compare to https://github.com/Intevel/nuxt-directus?

### ISSUE THREAD

**Issue by notflip** [becem-gharbi/nuxt-directus#68]
Just wondering, I'm not sure which one to use, thanks!

**Comment by becem-gharbi** [comment]
Hi, [nuxt-directus](https://nuxt.com/modules/directus) is the official module for Directus integration with Nuxt. I cannot compare because I'm not familiar with it.

**Comment by laportem** [comment]
I am very surprised there are more stars/up-takes for Intevel/nuxt-directus over becem-gharbi/nuxt-directus
I’ve tried both and to me, becem-gharbi/nuxt-directus is far far far better and much easier to work with.

**Comment by vanling** [comment]
@laportem <3 100% agree, this module is mostly a wrapper around the great SDK, where you can use the standard Directus Documentation.  With the exception of authenticationm @becem-gharbi  made that part 10x better. 

Sorry for 'hijacking' this issue for an appreciation moment ;) Thanks @becem-gharbi, the last releases are great updates <3
