### ISSUE TITLE
use runtimeConfig for module configuration

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/nuxt-directus#71]
Hi!

Is it possible to use [runtimeConfig](https://nuxt.com/docs/guide/going-further/runtime-config) with this plugin? At the moment the config values for this (wonderful) module are not using runtimeConfig.

Cheers!

Kees.

**Comment by appy-one** [comment]
I need this too

**Comment by MisterQnl** [comment]
This would be very helpfull indeed!

**Comment by becem-gharbi** [comment]
Hi,

I'm not sure I understand the issue. The options of the module are passed to the application via runtimeConfig. This is the standard. In this case you can read the options at `useRuntimeConfig().public.directus`.

https://github.com/becem-gharbi/nuxt-directus/blob/d0953a6ccc9fbde836661a2aa87891fade5b2b69/src/module.ts#L68

**Comment by keesvanbemmel** [comment]
There is no issue, I was under the impression it went outside the runtimeconfig.

Are there any examples of this module working with values from an .ENV file at runtime?

**Comment by vanling** [comment]
@keesvanbemmel try this :) 

```
runtimeConfig: {
    public: {
        directus:  {
            rest: {
                baseUrl: "http://localhost:8055",
            },
        }
    }
}
```

`NUXT_PUBLIC_DIRECTUS_REST_BASE_URL=https://api.directusinstance.com`
