### ISSUE TITLE
Failed to find useDirectusSession

### ISSUE THREAD

**Issue by jbmolle** [becem-gharbi/nuxt-directus#72]
In src/runtime/plugins/rest.ts, import { useDirectusSession } from '#imports' raises an error when auth.enabled is false because useDirectusSession is not auto imported anymore.

**Comment by becem-gharbi** [comment]
Thanks for reporting this bug. Now is solved on v2.2.1.
https://github.com/becem-gharbi/nuxt-directus/releases/tag/v2.2.1
