### ISSUE TITLE
useLocalePath in login config

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/nuxt-directus#80]
Hi,

Let me start with, this is not a bug but merely a question.

I'm using nuxt i18n in my project and whenever the auth middleware is hit it will forward me to /login (as is configured in nuxt.config.ts).

The question is, any idea on how to use locale paths in that configuration in nuxt.config.ts? The middleware should redirect me to /en/login or /nl/login for example.

Thanks!

**Comment by becem-gharbi** [comment]
Hi, the module expects redirection paths to be static. I'm not sure how to implement such feature. If you have any idea in mind please let me know.

As workaround I suggest adding a catch all route `[..._].vue` and perform redirection there.

```vue
<template>
  <div />
</template>

<script setup>
if (useRoute().path === '/login') {
    await navigateTo('/en/login')
} else {
    showError({ statusCode: 404, statusMessage: "Page Not Found" })
}
</script>
```

**Comment by keesvanbemmel** [comment]
Thanks for your pointer! What I did to mitigate this issue:
I created a global middleware that does this:
```
export default defineNuxtRouteMiddleware((to, from) => {
    const localePath = useLocalePath();
    if (to.path === '/login') {
      return navigateTo(localePath('/login'))
    }
    if (to.path === '/reset-password') {
      return navigateTo(localePath('/reset-password'))
    }
    if (to.path === '/auth/callback') {
      return navigateTo(localePath('/auth/callback'))
    }
  })
```
