### ISSUE TITLE
Refresh Logs Me Out

### ISSUE THREAD

**Issue by M-GRV** [becem-gharbi/nuxt-directus#83]
Hey! Been working on a new project and for some reason refreshing the page seems to log me out. But when using NuxtLink, it routes me fine throughout my app while maintaining auth.

Not sure if I am missing something. Everything is set as it should be I believe

**Comment by M-GRV** [comment]
switching to cookie from session fixed this. Is session not reccomended?

**Comment by becem-gharbi** [comment]
Hi, can you provide more info on this issue? a reproduction would be helpful.

**Comment by M-GRV** [comment]
> Hi, can you provide more info on this issue? a reproduction would be helpful.

Hey! It was a fresh install on a new nuxt app and when using sessions, refreshing the page logged me out. Switching to cookies fixed it.

I can switch my project back to session and provide you a link? I didn't see anything in console/logs

**Comment by becem-gharbi** [comment]
> I can switch my project back to session and provide you a link?

If you have a runnig preview we can check if `directus_session_token` cookie is correctly set on login.

**Comment by docloulou** [comment]
Hi, same here with the playground. directus and nuxt are on the same domain (localhost 3000/8055)
on refresh, i notice that cookie disapear 
(mode is cookie)

**Comment by moseskamau338** [comment]
Am having the same problem. In my case, the directus backend is at portal.domainx.com and the app is either local(127.0.0.1:3000) or online at domainx.com

Everytime I refresh, am logged out...here are some screenshots I just took a few minutes ago:

<img width="1101" alt="Screenshot 2024-05-29 at 10 35 40" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/3140269f-539e-4f56-923f-e4bd62fd7985">

<img width="1187" alt="Screenshot 2024-05-29 at 10 35 49" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/0de2d8e6-5346-4e1c-a46c-74d6e23645f8">

Here, I started by clearing everything in session and cookie as you can see


Then, I logged in, and all the values are filled correctly:
<img width="1210" alt="Screenshot 2024-05-29 at 10 36 10" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/87d2bcf6-0fa1-4b75-ac0f-18b0556f19d2">
<img width="1180" alt="Screenshot 2024-05-29 at 10 36 20" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/e1b14a41-7c1f-4281-a789-3bd1415c9098">


On refresh, this is what I get this:
<img width="1240" alt="Screenshot 2024-05-29 at 10 36 41" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/c6a5be9f-a17c-4eb3-bdb9-10c9cd3c574b">

My cookies are also gone
<img width="1169" alt="Screenshot 2024-05-29 at 10 48 38" src="https://github.com/becem-gharbi/nuxt-directus/assets/24386069/92958e89-621b-47be-9071-dccf0433dc6a">


I have had this issue for several months

**Comment by becem-gharbi** [comment]
![image](https://github.com/becem-gharbi/nuxt-directus/assets/99251251/8efab2e6-f8ad-46d1-9aab-049c9e787c1b)
