### ISSUE TITLE
SSO question

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/nuxt-directus#88]
Not an issue per se, but I can't seem to figure out why SSO login doesn't work.

Locally it works like a charm. Deployed the session cookie is set, but the local storage flags "directus_*" keep being 0 (or they change REALLY fast) and the expires flag is never set.

How can I debug this? Any pointers are more than welcome!

Regards,

Kees.

**Comment by keesvanbemmel** [comment]
So I think I found where my issues originated. We've deployed our SSR app to firebase and firebase functions. Whenever the session token cookie is fetched here is useDirectusSession it results in an empty cookie, so no session. I'm guessing this is due to the fact that getCookie from unjs H3 doesn't (always) pick up client cookies? I've looked at the request headers and the cookie is not there.

**Comment by vanling** [comment]
Are the frontend-app and directus-api on the same domain 
and is that cookie domain also configured in the Directus env?

**Comment by keesvanbemmel** [comment]
They weren't, now they are ~~and cookies seem to come across ok~~ but there are still no cookies server side.

However, the auth middleware always return to the login page. It seems like fetchUser is never called when going through the loginWithProvider flow? This the directus-auth-user state is never set?

**Comment by keesvanbemmel** [comment]
Ok, so for all you firebase hosting users. Keep this in mind:
https://firebase.google.com/docs/hosting/manage-cache#using_cookies

> When using Firebase Hosting together with Cloud Functions or Cloud Run, cookies are generally stripped from incoming requests. This is necessary to allow for efficient CDN [cache behavior](https://firebase.google.com/docs/hosting/manage-cache#set_cache-control). Only the specially-named __session cookie is permitted to pass through to the execution of your app.
