### ISSUE TITLE
Server side usage

### ISSUE THREAD

**Issue by mobius77** [becem-gharbi/nuxt-directus#89]
Please help.
How to use useDirectusRest on server side?
I can't import it.
Thanx

**Comment by becem-gharbi** [comment]
Hi, composables are auto-imported by Nuxt and can be called on SSR. What exactly is the issue?

**Comment by mobius77** [comment]
I'm trying to use:
`  let envs = await useDirectusRest(readItems('env', {
    fields: "e_id,e_uuid,isadmin,e_name",
  }));`

in the file: /server/api/v1/mynetpoint.get.ts

and got the error:
 ERROR  [nuxt] [request error] [unhandled] [500] useDirectusRest is not defined

**Comment by becem-gharbi** [comment]
Composables cannot be imported on server routes/plugins as they rely on Vue/Nuxt context [docs](https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables).
