### ISSUE TITLE
Meta data not available.

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#9]
Hi, Still in love with your module!

I love that it directly returns data but I think this part makes it also that meta data is not returned when requested.

https://github.com/becem-gharbi/nuxt-directus/blob/41d33ca8effbca834e65bc79177df8b6b02a05df/src/runtime/directus.ts#L91

<img width="717" alt="image" src="https://user-images.githubusercontent.com/50699657/231539183-94aa1847-1c67-4f4e-9bac-72059cabe30a.png">

https://docs.directus.io/reference/query.html#metadata

**Comment by becem-gharbi** [comment]
Thanks @vanling again for your support :)
Forgot to add the `meta` prop, this should solve the issue
```js
transportResponse = {
  raw: "",
  //@ts-ignore
  data: response._data["data"],
  meta: response._data["meta"],
  status: response.status,
  headers: response.headers,
};
```

**Comment by vanling** [comment]
@becem-gharbi Yes 👏 that worked. Should we add it only when meta is requested or just leave it there and let it return undefined?

**Comment by becem-gharbi** [comment]
We should leave it there [reference](https://github.com/directus/sdk/blob/main/src/base/transport.ts#L64), it will be treated by directus/sdk.

**Comment by becem-gharbi** [comment]
Just pushed a new patch to fix this bug
